# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.20

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /users/ug18df/Documents/rdf-store

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /users/ug18df/Documents/rdf-store

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /users/ug18df/Documents/rdf-store/CMakeFiles /users/ug18df/Documents/rdf-store//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /users/ug18df/Documents/rdf-store/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named my-RDF-store

# Build rule for target.
my-RDF-store: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 my-RDF-store
.PHONY : my-RDF-store

# fast build rule for target.
my-RDF-store/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/my-RDF-store.dir/build.make CMakeFiles/my-RDF-store.dir/build
.PHONY : my-RDF-store/fast

src/a_index.o: src/a_index.cpp.o
.PHONY : src/a_index.o

# target to build an object file
src/a_index.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/my-RDF-store.dir/build.make CMakeFiles/my-RDF-store.dir/src/a_index.cpp.o
.PHONY : src/a_index.cpp.o

src/a_index.i: src/a_index.cpp.i
.PHONY : src/a_index.i

# target to preprocess a source file
src/a_index.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/my-RDF-store.dir/build.make CMakeFiles/my-RDF-store.dir/src/a_index.cpp.i
.PHONY : src/a_index.cpp.i

src/a_index.s: src/a_index.cpp.s
.PHONY : src/a_index.s

# target to generate assembly for a file
src/a_index.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/my-RDF-store.dir/build.make CMakeFiles/my-RDF-store.dir/src/a_index.cpp.s
.PHONY : src/a_index.cpp.s

src/b_query_evaluate.o: src/b_query_evaluate.cpp.o
.PHONY : src/b_query_evaluate.o

# target to build an object file
src/b_query_evaluate.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/my-RDF-store.dir/build.make CMakeFiles/my-RDF-store.dir/src/b_query_evaluate.cpp.o
.PHONY : src/b_query_evaluate.cpp.o

src/b_query_evaluate.i: src/b_query_evaluate.cpp.i
.PHONY : src/b_query_evaluate.i

# target to preprocess a source file
src/b_query_evaluate.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/my-RDF-store.dir/build.make CMakeFiles/my-RDF-store.dir/src/b_query_evaluate.cpp.i
.PHONY : src/b_query_evaluate.cpp.i

src/b_query_evaluate.s: src/b_query_evaluate.cpp.s
.PHONY : src/b_query_evaluate.s

# target to generate assembly for a file
src/b_query_evaluate.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/my-RDF-store.dir/build.make CMakeFiles/my-RDF-store.dir/src/b_query_evaluate.cpp.s
.PHONY : src/b_query_evaluate.cpp.s

src/c_query_plan.o: src/c_query_plan.cpp.o
.PHONY : src/c_query_plan.o

# target to build an object file
src/c_query_plan.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/my-RDF-store.dir/build.make CMakeFiles/my-RDF-store.dir/src/c_query_plan.cpp.o
.PHONY : src/c_query_plan.cpp.o

src/c_query_plan.i: src/c_query_plan.cpp.i
.PHONY : src/c_query_plan.i

# target to preprocess a source file
src/c_query_plan.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/my-RDF-store.dir/build.make CMakeFiles/my-RDF-store.dir/src/c_query_plan.cpp.i
.PHONY : src/c_query_plan.cpp.i

src/c_query_plan.s: src/c_query_plan.cpp.s
.PHONY : src/c_query_plan.s

# target to generate assembly for a file
src/c_query_plan.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/my-RDF-store.dir/build.make CMakeFiles/my-RDF-store.dir/src/c_query_plan.cpp.s
.PHONY : src/c_query_plan.cpp.s

src/d_turtle_parse.o: src/d_turtle_parse.cpp.o
.PHONY : src/d_turtle_parse.o

# target to build an object file
src/d_turtle_parse.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/my-RDF-store.dir/build.make CMakeFiles/my-RDF-store.dir/src/d_turtle_parse.cpp.o
.PHONY : src/d_turtle_parse.cpp.o

src/d_turtle_parse.i: src/d_turtle_parse.cpp.i
.PHONY : src/d_turtle_parse.i

# target to preprocess a source file
src/d_turtle_parse.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/my-RDF-store.dir/build.make CMakeFiles/my-RDF-store.dir/src/d_turtle_parse.cpp.i
.PHONY : src/d_turtle_parse.cpp.i

src/d_turtle_parse.s: src/d_turtle_parse.cpp.s
.PHONY : src/d_turtle_parse.s

# target to generate assembly for a file
src/d_turtle_parse.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/my-RDF-store.dir/build.make CMakeFiles/my-RDF-store.dir/src/d_turtle_parse.cpp.s
.PHONY : src/d_turtle_parse.cpp.s

src/e_query_parse.o: src/e_query_parse.cpp.o
.PHONY : src/e_query_parse.o

# target to build an object file
src/e_query_parse.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/my-RDF-store.dir/build.make CMakeFiles/my-RDF-store.dir/src/e_query_parse.cpp.o
.PHONY : src/e_query_parse.cpp.o

src/e_query_parse.i: src/e_query_parse.cpp.i
.PHONY : src/e_query_parse.i

# target to preprocess a source file
src/e_query_parse.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/my-RDF-store.dir/build.make CMakeFiles/my-RDF-store.dir/src/e_query_parse.cpp.i
.PHONY : src/e_query_parse.cpp.i

src/e_query_parse.s: src/e_query_parse.cpp.s
.PHONY : src/e_query_parse.s

# target to generate assembly for a file
src/e_query_parse.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/my-RDF-store.dir/build.make CMakeFiles/my-RDF-store.dir/src/e_query_parse.cpp.s
.PHONY : src/e_query_parse.cpp.s

src/f_cli.o: src/f_cli.cpp.o
.PHONY : src/f_cli.o

# target to build an object file
src/f_cli.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/my-RDF-store.dir/build.make CMakeFiles/my-RDF-store.dir/src/f_cli.cpp.o
.PHONY : src/f_cli.cpp.o

src/f_cli.i: src/f_cli.cpp.i
.PHONY : src/f_cli.i

# target to preprocess a source file
src/f_cli.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/my-RDF-store.dir/build.make CMakeFiles/my-RDF-store.dir/src/f_cli.cpp.i
.PHONY : src/f_cli.cpp.i

src/f_cli.s: src/f_cli.cpp.s
.PHONY : src/f_cli.s

# target to generate assembly for a file
src/f_cli.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/my-RDF-store.dir/build.make CMakeFiles/my-RDF-store.dir/src/f_cli.cpp.s
.PHONY : src/f_cli.cpp.s

src/utils.o: src/utils.cpp.o
.PHONY : src/utils.o

# target to build an object file
src/utils.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/my-RDF-store.dir/build.make CMakeFiles/my-RDF-store.dir/src/utils.cpp.o
.PHONY : src/utils.cpp.o

src/utils.i: src/utils.cpp.i
.PHONY : src/utils.i

# target to preprocess a source file
src/utils.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/my-RDF-store.dir/build.make CMakeFiles/my-RDF-store.dir/src/utils.cpp.i
.PHONY : src/utils.cpp.i

src/utils.s: src/utils.cpp.s
.PHONY : src/utils.s

# target to generate assembly for a file
src/utils.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/my-RDF-store.dir/build.make CMakeFiles/my-RDF-store.dir/src/utils.cpp.s
.PHONY : src/utils.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... my-RDF-store"
	@echo "... src/a_index.o"
	@echo "... src/a_index.i"
	@echo "... src/a_index.s"
	@echo "... src/b_query_evaluate.o"
	@echo "... src/b_query_evaluate.i"
	@echo "... src/b_query_evaluate.s"
	@echo "... src/c_query_plan.o"
	@echo "... src/c_query_plan.i"
	@echo "... src/c_query_plan.s"
	@echo "... src/d_turtle_parse.o"
	@echo "... src/d_turtle_parse.i"
	@echo "... src/d_turtle_parse.s"
	@echo "... src/e_query_parse.o"
	@echo "... src/e_query_parse.i"
	@echo "... src/e_query_parse.s"
	@echo "... src/f_cli.o"
	@echo "... src/f_cli.i"
	@echo "... src/f_cli.s"
	@echo "... src/utils.o"
	@echo "... src/utils.i"
	@echo "... src/utils.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

